version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build/
  deploy:
    docker:
      - image: circleci/node:16
    steps:
      - attach_workspace:
          at: .
      - run: |
          mkdir -p Deploy/$(date +%Y-%m-%d)
          cp -r build/* Deploy/$(date +%Y-%m-%d)
      - run: |
          git config --global user.email "dakosta007@gmail.com"
          git config --global user.name "Dakosta007"
          git clone https://github.com/Dakosta007/RS-Module-2.git /tmp/repo
          cp -r Deploy/* /tmp/repo/Deploy/
          cd /tmp/repo
          git remote set-url origin https://github.com/Dakosta007/RS-Module-2.git
          git config --list
          git add Deploy/
          git commit -m "Deploy $(date +%Y-%m-%d)"         
          git push https://${PAT_GITHUB}@github.com/Dakosta007/RS-Module-2.git
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
